#!/bin/sh
#
# Copyright 2014 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#

set -e

if [ -d /usr/lib/file-drop-zone ]; then
  rm -rf /usr/lib/file-drop-zone
fi

if [ -d /var/file-drop-zone ]; then
  rm -rf /var/file-drop-zone
fi

if [ -d /tmp/file-drop-zone ]; then
  rm -rf /tmp/file-drop-zone
fi

if ! id file-drop-zone > /dev/null 2>&1 ; then
  adduser --system --no-create-home --group --disabled-password --shell /bin/false file-drop-zone
fi